# .github/workflows/generate_pdf.yml
name: Generar Documentación en PDF (Manual)

on:
  workflow_dispatch: # Permite la ejecución manual

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      # 1. Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
      
      # 2. Instalar docusaurus-prince-pdf
      - name: Instalar docusaurus-prince-pdf
        run: npm install docusaurus-prince-pdf

      # 3. Instalar Prince XML
      - name: Instalar Prince XML
        run: |
          echo "Instalando Prince XML..."
          curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
          tar zxf prince-14.2-linux-generic-x86_64.tar.gz
          cd prince-14.2-linux-generic-x86_64
          yes "" | sudo ./install.sh
          
      # 4. Construir el PDF (¡URL corregida!)
      - name: Construir PDF a partir del sitio desplegado
        run: npx docusaurus-prince-pdf -u https://cibercyl.ciberseguridad.wiki/docs/intro 
        
      # 5. Subir el artefacto (¡PATH corregido!)
      - name: Subir el artefacto PDF
        uses: actions/upload-artifact@v4
        with:
          name: documentacion-cibercyl-pdf
          path: pdf/cibercyl.ciberseguridad.wiki-docs-intro.pdf
          if-no-files-found: error